#!/bin/bash
source lenv/bin/activate
python app.py > /dev/null &
# Start ngrok HTTP tunnel on port 5000 in the background
ngrok http 5000 > /dev/null &

# Wait for ngrok to initialize
sleep 2

# Fetch the public URL from ngrok's API
NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')

# Display the URL
echo "Your ngrok URL is: $NGROK_URL"

